version: '3'
services:
  postgres:
    image: postgres:12.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
